passedt();

localStorage.removeItem("udmacau");
localStorage.removeItem("udmacau_e");


localStorage.setItem("DATA_e_r34y",'##From 7/Mar/2016<br>This route skips "Rua de Aveiro", "Hou Kong Middle School Taipa" and "Rua Evora/Flower City" stop. You may use "Nam Sun Garden Bldg.", "Va Pou Garden Bldg." or "Garden of Flower City" stop instead.');localStorage.setItem("DATA_r34y",'##2016年3月7日起<br>本線不停靠「亞威羅街」、「氹仔濠江中學」及「埃武拉街/花城」站，您可使用「南新花園」、「華寶花園」或「花城公園」站上落。');
localStorage.setItem("DATA_e_T348",'##From 7/Mar/2016<br>This stop is temporary suspended. You may use "Va Pou Garden Bldg." or "Garden of Flower City" stop instead.');localStorage.setItem("DATA_T348",'##2016年3月7日起<br>本站停用，您可使用「華寶花園」或「花城公園」站上落。');
localStorage.setItem("DATA_e_T349",'##From 7/Mar/2016<br>This stop is temporary suspended. You may use "Kingsville" stop instead.');localStorage.setItem("DATA_T349",'##2016年3月7日起<br>本站停用，您可使用「雍景灣」站上落。');
localStorage.setItem("DATA_e_T340",'##From 7/Mar/2016<br>Route 34 skips this stop. You may use "Nam Sun Garden Bldg." stop instead.');localStorage.setItem("DATA_T340",'##2016年3月7日起<br>路線34不停靠本站，您可使用「南新花園」站上落。');
localStorage.setItem("DATA_e_T361",'##From 16/Mar/2016<br>This stop is suspended. You may use "Rotunda da Piscina Olimpica" stop instead.');localStorage.setItem("DATA_T361",'##2016年3月16日起<br>本站停用，您可使用「奧林匹克游泳館圓形地」站上落。');
localStorage.setItem("DATA_e_r25y",'##From 16/Mar/2016<br>"Avenida do Estadio" stop is suspended. You may use "Rotunda da Piscina Olimpica" stop instead.');localStorage.setItem("DATA_r25y",'##2016年3月16日起<br>本線不停靠「運動場道」站，您可使用「奧林匹克游泳館圓形地」站上落。');
localStorage.setItem("DATA_e_r25Xx",'##From 16/Mar/2016<br>"Avenida do Estadio" stop is suspended. You may use "Rotunda da Piscina Olimpica" stop instead.');localStorage.setItem("DATA_r25Xx",'##2016年3月16日起<br>本線不停靠「運動場道」站，您可使用「奧林匹克游泳館圓形地」站上落。');
localStorage.setItem("DATA_e_r26Ay",'##From 16/Mar/2016<br>"Avenida do Estadio" stop is suspended. You may use "Rotunda da Piscina Olimpica" stop instead.');localStorage.setItem("DATA_r26Ay",'##2016年3月16日起<br>本線不停靠「運動場道」站，您可使用「奧林匹克游泳館圓形地」站上落。');
localStorage.setItem("DATA_e_r35x",'##From 16/Mar/2016<br>"Avenida do Estadio" stop is suspended. You may use "Rotunda da Piscina Olimpica" stop instead.');localStorage.setItem("DATA_r35x",'##2016年3月16日起<br>本線不停靠「運動場道」站，您可使用「奧林匹克游泳館圓形地」站上落。');
localStorage.setItem("DATA_e_rMT1x",'##From 16/Mar/2016<br>"Avenida do Estadio" stop is suspended. You may use "Rotunda da Piscina Olimpica" stop instead.');localStorage.setItem("DATA_rMT1x",'##2016年3月16日起<br>本線不停靠「運動場道」站，您可使用「奧林匹克游泳館圓形地」站上落。');
localStorage.setItem("DATA_e_rMT2x",'##From 16/Mar/2016<br>"Avenida do Estadio" stop is suspended. You may use "Rotunda da Piscina Olimpica" stop instead.');localStorage.setItem("DATA_rMT2x",'##2016年3月16日起<br>本線不停靠「運動場道」站，您可使用「奧林匹克游泳館圓形地」站上落。');
localStorage.setItem("DATA_e_rMT3x",'##From 16/Mar/2016<br>"Avenida do Estadio" stop is suspended. You may use "Rotunda da Piscina Olimpica" stop instead.');localStorage.setItem("DATA_rMT3x",'##2016年3月16日起<br>本線不停靠「運動場道」站，您可使用「奧林匹克游泳館圓形地」站上落。');
localStorage.setItem("DATA_e_rMT4x",'##From 16/Mar/2016<br>"Avenida do Estadio" stop is suspended. You may use "Rotunda da Piscina Olimpica" stop instead.');localStorage.setItem("DATA_rMT4x",'##2016年3月16日起<br>本線不停靠「運動場道」站，您可使用「奧林匹克游泳館圓形地」站上落。');
localStorage.setItem("DATA_e_M190",'##From 6/Apr/2016<br>This stop is suspended. For Rt. 9, go backward (to A-Ma Temple) about 130 m, Fong Son San Chun (Block 3) stop. For Rt. 1, 11, 21A, 26 and 55, go forward about 120 m, the temp. stop after footbridge. For other routes, go forward, Riviera Macau McDonald\'s stop.');localStorage.setItem("DATA_M190",'##2016年4月6日起<br>本站停用，乘搭9路線請向後行(往媽閣廟方向)約130米，到豐順新村第三座前的站點乘車；1、11、21A、26及55路線乘客請往前行約120米，到行人天橋之後的臨時站乘車；其餘路線請往前行至凱泉灣麥當勞門前站點乘車。');
localStorage.setItem("DATA_e_M204",'##From 6/Apr/2016<br>This stop is suspended. For Rt. 26, you need to walk forward quite far, the temp. stop is located after the footbridge near Riviera Macau. For other routes, go backward to use "Barra Terminus" for aboarding.');localStorage.setItem("DATA_M204",'##2016年4月6日起<br>本站停用，乘搭26路線需步行往凱泉灣行人天橋之後的臨時站乘車，其他路線的乘客請前往媽閣總站上落。');
localStorage.setItem("DATA_e_r2y",'##From 6/Apr/2016<br>"Largo do Pagode da Barra" and "Alm. Sergio/Barra" stop is suspended. Go forward (direction against A-Ma Temple), Riviera Macau McDonald\'s stop for aboarding.');localStorage.setItem("DATA_r2y",'##2016年4月6日起<br>「媽閣廟前地」及「河邊新街/媽閣」站停用，請往前行(往司打口方向)至凱泉灣麥當勞門前站點乘車。');
localStorage.setItem("DATA_e_r5y",'##From 6/Apr/2016<br>"Largo do Pagode da Barra" and "Alm. Sergio/Barra" stop is suspended. Go forward (direction against A-Ma Temple), Riviera Macau McDonald\'s stop for aboarding.');localStorage.setItem("DATA_r5y",'##2016年4月6日起<br>「媽閣廟前地」及「河邊新街/媽閣」站停用，請往前行(往司打口方向)至凱泉灣麥當勞門前站點乘車。');
localStorage.setItem("DATA_e_r7y",'##From 6/Apr/2016<br>"Largo do Pagode da Barra" and "Alm. Sergio/Barra" stop is suspended. Go forward (direction against A-Ma Temple), Riviera Macau McDonald\'s stop for aboarding.');localStorage.setItem("DATA_r7y",'##2016年4月6日起<br>「媽閣廟前地」及「河邊新街/媽閣」站停用，請往前行(往司打口方向)至凱泉灣麥當勞門前站點乘車。');
localStorage.setItem("DATA_e_r10y",'##From 6/Apr/2016<br>"Largo do Pagode da Barra" and "Alm. Sergio/Barra" stop is suspended. Go forward (direction against A-Ma Temple), Riviera Macau McDonald\'s stop for aboarding.');localStorage.setItem("DATA_r10y",'##2016年4月6日起<br>「媽閣廟前地」及「河邊新街/媽閣」站停用，請往前行(往司打口方向)至凱泉灣麥當勞門前站點乘車。');
localStorage.setItem("DATA_e_r10Ay",'##From 6/Apr/2016<br>"Largo do Pagode da Barra" and "Alm. Sergio/Barra" stop is suspended. Go forward (direction against A-Ma Temple), Riviera Macau McDonald\'s stop for aboarding.');localStorage.setItem("DATA_r10Ay",'##2016年4月6日起<br>「媽閣廟前地」及「河邊新街/媽閣」站停用，請往前行(往司打口方向)至凱泉灣麥當勞門前站點乘車。');
localStorage.setItem("DATA_e_rN3x",'##From 6/Apr/2016<br>"Largo do Pagode da Barra" and "Alm. Sergio/Barra" stop is suspended. Go forward (direction against A-Ma Temple), Riviera Macau McDonald\'s stop for aboarding.');localStorage.setItem("DATA_rN3x",'##2016年4月6日起<br>「媽閣廟前地」及「河邊新街/媽閣」站停用，請往前行(往司打口方向)至凱泉灣麥當勞門前站點乘車。');
localStorage.setItem("DATA_e_r1y",'##From 6/Apr/2016<br>"Largo do Pagode da Barra" and "Alm. Sergio/Barra" stop is suspended. Go forward (direction against A-Ma Temple), the temp. stop after footbridge for aboarding.');localStorage.setItem("DATA_r1y",'##2016年4月6日起<br>「媽閣廟前地」及「河邊新街/媽閣」站停用，請往前行(往司打口方向)，到行人天橋之後的臨時站乘車。');
localStorage.setItem("DATA_e_r11x",'##From 6/Apr/2016<br>"Largo do Pagode da Barra" and "Alm. Sergio/Barra" stop is suspended. Go forward (direction against A-Ma Temple), the temp. stop after footbridge for aboarding.');localStorage.setItem("DATA_r11x",'##2016年4月6日起<br>「媽閣廟前地」及「河邊新街/媽閣」站停用，請往前行(往司打口方向)，到行人天橋之後的臨時站乘車。');
localStorage.setItem("DATA_e_r21Ax",'##From 6/Apr/2016<br>"Largo do Pagode da Barra" and "Alm. Sergio/Barra" stop is suspended. Go forward (direction against A-Ma Temple), the temp. stop after footbridge for aboarding.');localStorage.setItem("DATA_r21Ax",'##2016年4月6日起<br>「媽閣廟前地」及「河邊新街/媽閣」站停用，請往前行(往司打口方向)，到行人天橋之後的臨時站乘車。');
localStorage.setItem("DATA_e_r26y",'##From 6/Apr/2016<br>"Largo do Pagode da Barra" and "Alm. Sergio/Barra" stop is suspended. Go forward (direction against A-Ma Temple), the temp. stop after footbridge for aboarding.');localStorage.setItem("DATA_r26y",'##2016年4月6日起<br>「媽閣廟前地」及「河邊新街/媽閣」站停用，請往前行(往司打口方向)，到行人天橋之後的臨時站乘車。');
localStorage.setItem("DATA_e_r55x",'##From 6/Apr/2016<br>"Largo do Pagode da Barra" and "Alm. Sergio/Barra" stop is suspended. Go forward (direction against A-Ma Temple), the temp. stop after footbridge for aboarding.');localStorage.setItem("DATA_r55x",'##2016年4月6日起<br>「媽閣廟前地」及「河邊新街/媽閣」站停用，請往前行(往司打口方向)，到行人天橋之後的臨時站乘車。');
localStorage.setItem("DATA_e_r9x",'##From 6/Apr/2016<br>"Largo do Pagode da Barra" and "Alm. Sergio/Barra" stop is suspended. Go to the temp. stop between these two stop, Fong Son San Chun (Block 3) stop for aboarding.');localStorage.setItem("DATA_r9x",'##2016年4月6日起<br>「媽閣廟前地」及「河邊新街/媽閣」站停用，請到兩站間豐順新村第三座前的站點乘車。');
localStorage.setItem("DATA_e_rN5x",'##From now on,<br>Rt N5 becomes a route back and forth Seac Pai Van and Lisboa, no stop is located at airport nor the two ferry terminal.');localStorage.setItem("DATA_rN5x",'##即日起<br>本線改為往返石排灣至亞馬喇的雙向路線，不再行經機場及各碼頭。');

localStorage.setItem("DATA_e_r18y",'##From 6/Apr/2016<br>"Largo do Pagode da Barra" and "Alm. Sergio/Barra" stop is suspended. Go forward (direction against A-Ma Temple), Riviera Macau McDonald\'s stop for aboarding.<br>&nbsp;<br>15/Apr - 4/May/2016<br>"Rua das Estalagens" and "R. Cinco Outubro" stop are suspended. You may use the temp. stop located at the intersection of Rua dos Faitiões and Rua da Tercena.');localStorage.setItem("DATA_r18y",'##2016年4月6日起<br>「媽閣廟前地」及「河邊新街/媽閣」站停用，請往前行(往司打口方向)至凱泉灣麥當勞門前站點乘車。<br>&nbsp;<br>2016年4月15日至5月4日<br>「草堆街」站及「十月初五街」站停用，您可使用快艇頭街與果欄街交界的臨時站上落。');

if((vers!="v69")){
    var link = '<a ontouchstart="localStorage.setItem(\'getgetmacau\',\'\');localStorage.setItem(\'udmacau\',\'\');localStorage.setItem(\'udmacau_e\',\'\');window.location.href=\'https://play.google.com/store/apps/details?id=com.locmacau&apk\'" class="upd-icon">';

    localStorage.setItem("udmacau",link+"<b>澳門出行易 V4.3.1</b><u>更新路線</u><div>檢視</div></a>");
    localStorage.setItem("udmacau_e",link+"<b>Macau EasyGo V4.3.1</b><u>Route Info Updated</u><div>VIEW</div></a>");
    window.location.reload();
}