passedt();

localStorage.removeItem("udmacau");
localStorage.removeItem("udmacau_e");

localStorage.setItem('DATA_e_M135','##23-25/Aug/2016, Every 23H30-06H00<br>Only Rt 18 stops at this stop. For other routes, no temp stop is set.');localStorage.setItem('DATA_M135','##2016年8月23至25日 每晚十一時半至清晨六時<br>只有路線18維持停靠本站，其他路線不設臨時站。');
localStorage.setItem('DATA_e_M167','##23-25/Aug/2016, Every 23H30-06H00<br>This stop is suspended. No temp stop is set.');localStorage.setItem('DATA_M167','##2016年8月23至25日 每晚十一時半至清晨六時<br>本站停用，不設臨時站。');
localStorage.setItem('DATA_e_M137','##23-25/Aug/2016, Every 23H30-06H00<br>Only Rt 1, 18, 26, MT4 stops at this stop. Go "Ponte Horta Terminus" for Rt 3A or "Alm. Sergio/Trav. Lido" for other routes.');localStorage.setItem('DATA_M137','##2016年8月23至25日 每晚十一時半至清晨六時<br>只有路線1、18、26及MT4維持停靠本站；乘搭3A路線請前往「司打口總站」，其餘路線請使用「河邊新街/李道巷」站。');
localStorage.setItem('DATA_e_M170','##23-25/Aug/2016, Every 23H30-06H00<br>Only Rt 10B stops at this stop. For other routes, no temp stop is set.');localStorage.setItem('DATA_M170','##2016年8月23至25日 每晚十一時半至清晨六時<br>只有路線10B維持停靠本站，其他路線不設臨時站。');
localStorage.setItem('DATA_e_M168','##23-25/Aug/2016, Every 23H30-06H00<br>Rt 6A and 28B skip this stop.');localStorage.setItem('DATA_M168','##2016年8月23至25日 每晚十一時半至清晨六時<br>路線6A及28B不停靠本站。');
localStorage.setItem('DATA_e_M143','##23-25/Aug/2016, Every 23H30-06H00<br>This stop is suspended. No temp stop is set.');localStorage.setItem('DATA_M143','##2016年8月23至25日 每晚十一時半至清晨六時<br>本站停用，不設臨時站。');
localStorage.setItem('DATA_e_M163','##23-25/Aug/2016, Every 23H30-06H00<br>Rt 28B skips this stop. Use "Praceta 1 de Outubro" stop instead.');localStorage.setItem('DATA_M163','##2016年8月23至25日 每晚十一時半至清晨六時<br>路線28B不停靠本站，可使用「十月一日前地」站上落。');

localStorage.setItem('DATA_e_r2y','##23-25/Aug/2016, Every 23H30-06H00<br>This route skips "R. das Lorchas", "San Malo/Tai Fung Bank", "Nam Van/Si Toi Commercial Bldg" stop. You need to use "Alm. Sergio/Trav. Lido" or "Rua do Campo" stop.');localStorage.setItem('DATA_r2y','##2016年8月23至25日 每晚十一時半至清晨六時<br>本線不停靠「火船頭街」、「新馬路/大豐」、「南灣大馬路/時代」站，乘客需使用「河邊新街/李道巷」或「水坑尾街」站上落。');
localStorage.setItem('DATA_e_r3x','##23-25/Aug/2016, Every 23H30-06H00<br>This route skips "San Malo/Tai Fung Bank", "Av. Infante D. Henrique" stop. You need to use "Pak Kong Public Car Park" or "Praca Ferreira Amaral" stop.');localStorage.setItem('DATA_r3x','##2016年8月23至25日 每晚十一時半至清晨六時<br>本線不停靠「新馬路/大豐」、「殷皇子馬路」站，乘客需使用「栢港停車場」或「亞馬喇前地」站上落。');
localStorage.setItem('DATA_e_r3Ay','##23-25/Aug/2016, Every 23H30-06H00<br>This route skips "R. das Lorchas", "San Malo/Tai Fung Bank", "Av. Infante D. Henrique" stop. You need to use "Ponte Horta Terminus" or "Praca Ferreira Amaral" stop.');localStorage.setItem('DATA_r3Ay','##2016年8月23至25日 每晚十一時半至清晨六時<br>本線不停靠「火船頭街」、「新馬路/大豐」、「殷皇子馬路」站，乘客需使用「司打口總站」或「亞馬喇前地」站上落。');
localStorage.setItem('DATA_e_r3Xx','##23-25/Aug/2016, Every 23H30-06H00<br>This route skips "San Malo/Tai Fung Bank", "Av. Infante D. Henrique" stop. You need to use "Pak Kong Public Car Park" or "Praca Ferreira Amaral" stop.');localStorage.setItem('DATA_r3Xx','##2016年8月23至25日 每晚十一時半至清晨六時<br>本線不停靠「新馬路/大豐」、「殷皇子馬路」站，乘客需使用「栢港停車場」或「亞馬喇前地」站上落。');
localStorage.setItem('DATA_e_r5y','##23-25/Aug/2016, Every 23H30-06H00<br>This route skips "R. das Lorchas", "San Malo/Tai Fung Bank", "Nam Van/Si Toi Commercial Bldg" stop. You need to use "Alm. Sergio/Trav. Lido" or "Rua do Campo" stop.');localStorage.setItem('DATA_r5y','##2016年8月23至25日 每晚十一時半至清晨六時<br>本線不停靠「火船頭街」、「新馬路/大豐」、「南灣大馬路/時代」站，乘客需使用「河邊新街/李道巷」或「水坑尾街」站上落。');
localStorage.setItem('DATA_e_r6Ax','##23-25/Aug/2016, Every 23H30-06H00<br>This route skips "San Malo/Tai Fung Bank", "Nam Van/Si Toi Commercial Bldg" and "Nam Van/Sao Francisco Garden" stop. You need to use "Pak Kong Public Car Park" or "S. Francisco/Barracks" stop.');localStorage.setItem('DATA_r6Ax','##2016年8月23至25日 每晚十一時半至清晨六時<br>本線不停靠「新馬路/大豐」、「南灣大馬路/時代」、「八角亭」站，乘客需使用「栢港停車場」或「加思欄馬路」站上落。');
localStorage.setItem('DATA_e_r7y','##23-25/Aug/2016, Every 23H30-06H00<br>This route skips "R. das Lorchas", "San Malo/Tai Fung Bank", "Nam Van/Si Toi Commercial Bldg" stop. You need to use "Alm. Sergio/Trav. Lido" or "Rua do Campo" stop.');localStorage.setItem('DATA_r7y','##2016年8月23至25日 每晚十一時半至清晨六時<br>本線不停靠「火船頭街」、「新馬路/大豐」、「南灣大馬路/時代」站，乘客需使用「河邊新街/李道巷」或「水坑尾街」站上落。');
localStorage.setItem('DATA_e_r10y','##23-25/Aug/2016, Every 23H30-06H00<br>This route skips "R. das Lorchas", "San Malo/Tai Fung Bank", "Av. Infante D. Henrique" stop. You need to use "Alm. Sergio/Trav. Lido" or "Praca Ferreira Amaral" stop.');localStorage.setItem('DATA_r10y','##2016年8月23至25日 每晚十一時半至清晨六時<br>本線不停靠「火船頭街」、「新馬路/大豐」、「殷皇子馬路」站，乘客需使用「河邊新街/李道巷」或「亞馬喇前地」站上落。');
localStorage.setItem('DATA_e_r10Ay','##23-25/Aug/2016, Every 23H30-06H00<br>This route skips "R. das Lorchas", "San Malo/Tai Fung Bank", "Av. Infante D. Henrique" stop. You need to use "Alm. Sergio/Trav. Lido" or "Praca Ferreira Amaral" stop.');localStorage.setItem('DATA_r10Ay','##2016年8月23至25日 每晚十一時半至清晨六時<br>本線不停靠「火船頭街」、「新馬路/大豐」、「殷皇子馬路」站，乘客需使用「河邊新街/李道巷」或「亞馬喇前地」站上落。');
localStorage.setItem('DATA_e_r11x','##23-25/Aug/2016, Every 23H30-06H00<br>This route skips "R. das Lorchas", "San Malo/Rua Camilo Pessanha", "Av. Infante D. Henrique" stop. You need to use "Alm. Sergio/Trav. Lido" or "Praca Ferreira Amaral" stop.');localStorage.setItem('DATA_r11x','##2016年8月23至25日 每晚十一時半至清晨六時<br>本線不停靠「火船頭街」、「新馬路/爐石塘」、「殷皇子馬路」站，乘客需使用「河邊新街/李道巷」或「亞馬喇前地」站上落。');
localStorage.setItem('DATA_e_r16x','##23-25/Aug/2016, Every 23H30-06H00<br>This route skips "Nam Van/Si Toi Commercial Bldg" stop. You need to use "Rua do Campo" stop.');localStorage.setItem('DATA_r16x','##2016年8月23至25日 每晚十一時半至清晨六時<br>本線不停靠「南灣大馬路/時代」站，乘客需使用「水坑尾街」站上落。');
localStorage.setItem('DATA_e_r21Ay','##23-25/Aug/2016, Every 23H30-06H00<br>This route skips "R. das Lorchas", "San Malo/Rua Camilo Pessanha", "Av. Infante D. Henrique" stop. You need to use "Alm. Sergio/Trav. Lido" or "Praca Ferreira Amaral" stop.');localStorage.setItem('DATA_r21Ay','##2016年8月23至25日 每晚十一時半至清晨六時<br>本線不停靠「火船頭街」、「新馬路/爐石塘」、「殷皇子馬路」站，乘客需使用「河邊新街/李道巷」或「亞馬喇前地」站上落。');
localStorage.setItem('DATA_e_r26Ax','##23-25/Aug/2016, Every 23H30-06H00<br>This route skips "San Malo/Rua Camilo Pessanha", "Av. Infante D. Henrique" stop. You need to use "Pak Kong Public Car Park" or "Praca Ferreira Amaral" stop.');localStorage.setItem('DATA_r26Ax','##2016年8月23至25日 每晚十一時半至清晨六時<br>本線不停靠「新馬路/爐石塘」、「殷皇子馬路」站，乘客需使用「栢港停車場」或「亞馬喇前地」站上落。');
localStorage.setItem('DATA_e_r28Bx','##23-25/Aug/2016, Every 23H30-06H00<br>This route skips "Nam Van/Si Toi Commercial Bldg", "Nam Van/Sao Francisco Garden", "Lopo S. Carvalho/Hotel Lisboa" stop. You need to use "S. Agostinho" or "Praceta 1 de Outubro" stop.');localStorage.setItem('DATA_r28Bx','##2016年8月23至25日 每晚十一時半至清晨六時<br>本線不停靠「南灣大馬路/時代」、「八角亭」、「賈羅布/葡京」站，乘客需使用「巴掌圍」或「十月一日前地」站上落。');
localStorage.setItem('DATA_e_r33x','##23-25/Aug/2016, Every 23H30-06H00<br>This route skips "San Malo/Rua Camilo Pessanha", "Av. Infante D. Henrique" stop. You need to use "Pak Kong Public Car Park" or "Praca Ferreira Amaral" stop.');localStorage.setItem('DATA_r33x','##2016年8月23至25日 每晚十一時半至清晨六時<br>本線不停靠「新馬路/爐石塘」、「殷皇子馬路」站，乘客需使用「栢港停車場」或「亞馬喇前地」站上落。');
localStorage.setItem('DATA_e_rN1Bx','##23-25/Aug/2016, Every 23H30-06H00<br>This route skips "San Malo/Tai Fung Bank", "Av. Infante D. Henrique" stop. You need to use "Pak Kong Public Car Park" or "Praca Ferreira Amaral" stop.');localStorage.setItem('DATA_rN1Bx','##2016年8月23至25日 每晚十一時半至清晨六時<br>本線不停靠「新馬路/大豐」、「殷皇子馬路」站，乘客需使用「栢港停車場」或「亞馬喇前地」站上落。');
localStorage.setItem('DATA_e_rN3x','##23-25/Aug/2016, Every 23H30-06H00<br>This route skips "R. das Lorchas", "San Malo/Tai Fung Bank", "Av. Infante D. Henrique" stop. You need to use "Alm. Sergio/Trav. Lido" or "Praca Ferreira Amaral" stop.');localStorage.setItem('DATA_rN3x','##2016年8月23至25日 每晚十一時半至清晨六時<br>本線不停靠「火船頭街」、「新馬路/大豐」、「殷皇子馬路」站，乘客需使用「河邊新街/李道巷」或「亞馬喇前地」站上落。');

if((vers!="v78")){
    var link = '<a ontouchstart="localStorage.setItem(\'getgetmacau\',\'\');localStorage.setItem(\'udmacau\',\'\');localStorage.setItem(\'udmacau_e\',\'\');window.location.href=\'https://play.google.com/store/apps/details?id=com.locmacau&apk\'" class="upd-icon">';

    localStorage.setItem("udmacau",link+"<b>澳門出行易 V4.3.8</b><u>程式修復及優化</u><div>檢視</div></a>");
    localStorage.setItem("udmacau_e",link+"<b>Macau EasyGo V4.3.8</b><u>Bug Fixing and Enhancement</u><div>VIEW</div></a>");
    window.location.reload();
}
